// flow-typed signature: 6de1ebc4ff9dc79cb1ef52189eae357a
// flow-typed version: <<STUB>>/oncoprintjs_v^1.0.87/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'oncoprintjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'oncoprintjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'oncoprintjs/dist/oncoprint.bundle' {
  declare module.exports: any;
}

declare module 'oncoprintjs/karma.conf' {
  declare module.exports: any;
}

declare module 'oncoprintjs/rules/geneticrules' {
  declare module.exports: any;
}

declare module 'oncoprintjs/src/js/binarysearch' {
  declare module.exports: any;
}

declare module 'oncoprintjs/src/js/CachedProperty' {
  declare module.exports: any;
}

declare module 'oncoprintjs/src/js/clustering' {
  declare module.exports: any;
}

declare module 'oncoprintjs/src/js/extractrgba' {
  declare module.exports: any;
}

declare module 'oncoprintjs/src/js/haselementsininterval' {
  declare module.exports: any;
}

declare module 'oncoprintjs/src/js/heatmapcolors' {
  declare module.exports: any;
}

declare module 'oncoprintjs/src/js/main' {
  declare module.exports: any;
}

declare module 'oncoprintjs/src/js/makesvgelement' {
  declare module.exports: any;
}

declare module 'oncoprintjs/src/js/oncoprint' {
  declare module.exports: any;
}

declare module 'oncoprintjs/src/js/oncoprintlabelview' {
  declare module.exports: any;
}

declare module 'oncoprintjs/src/js/oncoprintlegendrenderer' {
  declare module.exports: any;
}

declare module 'oncoprintjs/src/js/oncoprintminimapview' {
  declare module.exports: any;
}

declare module 'oncoprintjs/src/js/oncoprintmodel' {
  declare module.exports: any;
}

declare module 'oncoprintjs/src/js/oncoprintruleset' {
  declare module.exports: any;
}

declare module 'oncoprintjs/src/js/oncoprintshape' {
  declare module.exports: any;
}

declare module 'oncoprintjs/src/js/oncoprintshapetosvg' {
  declare module.exports: any;
}

declare module 'oncoprintjs/src/js/oncoprintshapetovertexes' {
  declare module.exports: any;
}

declare module 'oncoprintjs/src/js/oncoprintsvgcellview' {
  declare module.exports: any;
}

declare module 'oncoprintjs/src/js/oncoprinttooltip' {
  declare module.exports: any;
}

declare module 'oncoprintjs/src/js/oncoprinttrackinfoview' {
  declare module.exports: any;
}

declare module 'oncoprintjs/src/js/oncoprinttrackoptionsview' {
  declare module.exports: any;
}

declare module 'oncoprintjs/src/js/oncoprintwebglcellview' {
  declare module.exports: any;
}

declare module 'oncoprintjs/src/js/oncoprintzoomslider' {
  declare module.exports: any;
}

declare module 'oncoprintjs/src/js/polyfill' {
  declare module.exports: any;
}

declare module 'oncoprintjs/src/js/svgfactory' {
  declare module.exports: any;
}

declare module 'oncoprintjs/src/js/workers/clustering-worker' {
  declare module.exports: any;
}

declare module 'oncoprintjs/src/test/test' {
  declare module.exports: any;
}

declare module 'oncoprintjs/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'oncoprintjs/dist/oncoprint.bundle.js' {
  declare module.exports: $Exports<'oncoprintjs/dist/oncoprint.bundle'>;
}
declare module 'oncoprintjs/karma.conf.js' {
  declare module.exports: $Exports<'oncoprintjs/karma.conf'>;
}
declare module 'oncoprintjs/rules/geneticrules.js' {
  declare module.exports: $Exports<'oncoprintjs/rules/geneticrules'>;
}
declare module 'oncoprintjs/src/js/binarysearch.js' {
  declare module.exports: $Exports<'oncoprintjs/src/js/binarysearch'>;
}
declare module 'oncoprintjs/src/js/CachedProperty.js' {
  declare module.exports: $Exports<'oncoprintjs/src/js/CachedProperty'>;
}
declare module 'oncoprintjs/src/js/clustering.js' {
  declare module.exports: $Exports<'oncoprintjs/src/js/clustering'>;
}
declare module 'oncoprintjs/src/js/extractrgba.js' {
  declare module.exports: $Exports<'oncoprintjs/src/js/extractrgba'>;
}
declare module 'oncoprintjs/src/js/haselementsininterval.js' {
  declare module.exports: $Exports<'oncoprintjs/src/js/haselementsininterval'>;
}
declare module 'oncoprintjs/src/js/heatmapcolors.js' {
  declare module.exports: $Exports<'oncoprintjs/src/js/heatmapcolors'>;
}
declare module 'oncoprintjs/src/js/main.js' {
  declare module.exports: $Exports<'oncoprintjs/src/js/main'>;
}
declare module 'oncoprintjs/src/js/makesvgelement.js' {
  declare module.exports: $Exports<'oncoprintjs/src/js/makesvgelement'>;
}
declare module 'oncoprintjs/src/js/oncoprint.js' {
  declare module.exports: $Exports<'oncoprintjs/src/js/oncoprint'>;
}
declare module 'oncoprintjs/src/js/oncoprintlabelview.js' {
  declare module.exports: $Exports<'oncoprintjs/src/js/oncoprintlabelview'>;
}
declare module 'oncoprintjs/src/js/oncoprintlegendrenderer.js' {
  declare module.exports: $Exports<'oncoprintjs/src/js/oncoprintlegendrenderer'>;
}
declare module 'oncoprintjs/src/js/oncoprintminimapview.js' {
  declare module.exports: $Exports<'oncoprintjs/src/js/oncoprintminimapview'>;
}
declare module 'oncoprintjs/src/js/oncoprintmodel.js' {
  declare module.exports: $Exports<'oncoprintjs/src/js/oncoprintmodel'>;
}
declare module 'oncoprintjs/src/js/oncoprintruleset.js' {
  declare module.exports: $Exports<'oncoprintjs/src/js/oncoprintruleset'>;
}
declare module 'oncoprintjs/src/js/oncoprintshape.js' {
  declare module.exports: $Exports<'oncoprintjs/src/js/oncoprintshape'>;
}
declare module 'oncoprintjs/src/js/oncoprintshapetosvg.js' {
  declare module.exports: $Exports<'oncoprintjs/src/js/oncoprintshapetosvg'>;
}
declare module 'oncoprintjs/src/js/oncoprintshapetovertexes.js' {
  declare module.exports: $Exports<'oncoprintjs/src/js/oncoprintshapetovertexes'>;
}
declare module 'oncoprintjs/src/js/oncoprintsvgcellview.js' {
  declare module.exports: $Exports<'oncoprintjs/src/js/oncoprintsvgcellview'>;
}
declare module 'oncoprintjs/src/js/oncoprinttooltip.js' {
  declare module.exports: $Exports<'oncoprintjs/src/js/oncoprinttooltip'>;
}
declare module 'oncoprintjs/src/js/oncoprinttrackinfoview.js' {
  declare module.exports: $Exports<'oncoprintjs/src/js/oncoprinttrackinfoview'>;
}
declare module 'oncoprintjs/src/js/oncoprinttrackoptionsview.js' {
  declare module.exports: $Exports<'oncoprintjs/src/js/oncoprinttrackoptionsview'>;
}
declare module 'oncoprintjs/src/js/oncoprintwebglcellview.js' {
  declare module.exports: $Exports<'oncoprintjs/src/js/oncoprintwebglcellview'>;
}
declare module 'oncoprintjs/src/js/oncoprintzoomslider.js' {
  declare module.exports: $Exports<'oncoprintjs/src/js/oncoprintzoomslider'>;
}
declare module 'oncoprintjs/src/js/polyfill.js' {
  declare module.exports: $Exports<'oncoprintjs/src/js/polyfill'>;
}
declare module 'oncoprintjs/src/js/svgfactory.js' {
  declare module.exports: $Exports<'oncoprintjs/src/js/svgfactory'>;
}
declare module 'oncoprintjs/src/js/workers/clustering-worker.js' {
  declare module.exports: $Exports<'oncoprintjs/src/js/workers/clustering-worker'>;
}
declare module 'oncoprintjs/src/test/test.js' {
  declare module.exports: $Exports<'oncoprintjs/src/test/test'>;
}
declare module 'oncoprintjs/webpack.config.js' {
  declare module.exports: $Exports<'oncoprintjs/webpack.config'>;
}
